### ISSUE TITLE
Client crashes when joining multi

### ISSUE THREAD

**Issue by MCCheater** [MCmodding4K/SkillClient#181]
Hi,

recently I tried to use SkillClient in multi however it crashes every time when joining the server.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  skillclient (skillclient-1.12.2-b10.7.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 6/3/18 4:24 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78750_j(PlayerControllerMP.java:373)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:346)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1722)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78750_j(PlayerControllerMP.java:373)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:346)
-- Affected level --
Details:
	Level name: MpServer
	All players: 0 total; []
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 0 total; []
	Retry entities: 0 total; []
	Server brand: ~~ERROR~~ NullPointerException: null
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2738)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by MCmodding4K** [comment]
can you send the whole log files? I can't reproduce this nor i have an idea why this happens, it's only code i don't modify

**Comment by MCCheater** [comment]
[crash-2018-06-03_04.24.52-client.txt](https://github.com/MCmodding4K/SkillClient/files/2073419/crash-2018-06-03_04.24.52-client.txt)
The log file.

**Comment by MCmodding4K** [comment]
server.skillclient.com/skillclient-b11.5-debug.jar
Add Java-VM-Option: -DskillLog=<path to downloads>/log.txt
