### ISSUE TITLE
crash when joining multiplayer or singleplayer

### ISSUE THREAD

**Issue by hezii** [MCmodding4K/SkillClient#189]
just installed the latest version of skillClient and when i join servers or singleplayer world, it crashes.
log report below

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 6/24/19 10:32 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at skill.cr.a(Unknown Source)
	at skill.ao.b(Unknown Source)
	at skill.I.c(Unknown Source)
	at skill.pC.a(Unknown Source)
	at skill.yQ.a(Unknown Source)
	at skill.mW.c(Unknown Source)
	at skill.mW.a(Unknown Source)
	at skill.cV.main(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at skill.cr.a(Unknown Source)
	at skill.ao.b(Unknown Source)
	at skill.I.c(Unknown Source)
	at skill.pC.a(Unknown Source)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [nP['Unliv'/641, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Chunk stats: MultiplayerChunkCache: 53, 53
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 1 total; [nP['Unliv'/641, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Retry entities: 0 total; []
	Server brand: vanilla
	Server type: Integrated singleplayer server
Stacktrace:
	at skill.vV.a(Unknown Source)
	at skill.mW.a(Unknown Source)
	at skill.mW.a(Unknown Source)
	at skill.cV.main(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.13.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 589334232 bytes (562 MB) / 872415232 bytes (832 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: skillclient-1.13.2
	LWJGL: 3.1.6 build 14
	OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 10.18.10.4358, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Celeron(R) CPU N2930 @ 1.83GHz

**Comment by hezii** [comment]
also forgot to mention that when i try to add "Online" Alts, and I attempt to put username and password, it doesn't work. As in, what i am typing doesn't show up in the GUI.

**Comment by HummeL777** [comment]
Solved a problem?
